name: "@ubiquity-os-marketplace/personal-agent"

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      ref:
        description: "Ref"

jobs:
  compute:
    name: "LLM Reply"
    runs-on: ubuntu-latest
    permissions: write-all
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'development' }}

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install tree package
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: execute directive
        run: node ./dist/index.js
        id: plugin-personal-agent
        env:
          PERSONAL_AGENT_PAT_CLASSIC: ${{ secrets.PERSONAL_AGENT_PAT_CLASSIC }}
          PLUGIN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
